/* -----------------------------------------------------------------------------
 * Visitor.java
 * -----------------------------------------------------------------------------
 *
 * Producer : com.parse2.aparse.Parser 2.3
 * Produced : Fri Apr 12 10:40:21 MUT 2013
 *
 * -----------------------------------------------------------------------------
 */

package com.litecoding.smali2java.builder;

import com.litecoding.smali2java.parser.Terminal_NumericValue;
import com.litecoding.smali2java.parser.Terminal_StringValue;
import com.litecoding.smali2java.parser.cmd.*;
import com.litecoding.smali2java.parser.cmd.and7or7xor.and.Rule_cmdAndInt;
import com.litecoding.smali2java.parser.cmd.and7or7xor.and.Rule_cmdAndInt2addr;
import com.litecoding.smali2java.parser.cmd.and7or7xor.and.Rule_cmdAndIntLit16;
import com.litecoding.smali2java.parser.cmd.and7or7xor.and.Rule_cmdAndIntLit8;
import com.litecoding.smali2java.parser.cmd.and7or7xor.and.Rule_cmdAndLong;
import com.litecoding.smali2java.parser.cmd.and7or7xor.and.Rule_cmdAndLong2addr;
import com.litecoding.smali2java.parser.cmd.and7or7xor.or.Rule_cmdOrInt;
import com.litecoding.smali2java.parser.cmd.and7or7xor.or.Rule_cmdOrInt2addr;
import com.litecoding.smali2java.parser.cmd.and7or7xor.or.Rule_cmdOrIntLit16;
import com.litecoding.smali2java.parser.cmd.and7or7xor.or.Rule_cmdOrIntLit8;
import com.litecoding.smali2java.parser.cmd.and7or7xor.or.Rule_cmdOrLong;
import com.litecoding.smali2java.parser.cmd.and7or7xor.or.Rule_cmdOrLong2addr;
import com.litecoding.smali2java.parser.cmd.and7or7xor.xor.Rule_cmdXorInt;
import com.litecoding.smali2java.parser.cmd.and7or7xor.xor.Rule_cmdXorInt2addr;
import com.litecoding.smali2java.parser.cmd.and7or7xor.xor.Rule_cmdXorIntLit16;
import com.litecoding.smali2java.parser.cmd.and7or7xor.xor.Rule_cmdXorIntLit8;
import com.litecoding.smali2java.parser.cmd.and7or7xor.xor.Rule_cmdXorLong;
import com.litecoding.smali2java.parser.cmd.and7or7xor.xor.Rule_cmdXorLong2addr;
import com.litecoding.smali2java.parser.cmd.asmd.add.Rule_cmdAddDouble;
import com.litecoding.smali2java.parser.cmd.asmd.add.Rule_cmdAddDouble2addr;
import com.litecoding.smali2java.parser.cmd.asmd.add.Rule_cmdAddFloat;
import com.litecoding.smali2java.parser.cmd.asmd.add.Rule_cmdAddFloat2addr;
import com.litecoding.smali2java.parser.cmd.asmd.add.Rule_cmdAddInt;
import com.litecoding.smali2java.parser.cmd.asmd.add.Rule_cmdAddInt2addr;
import com.litecoding.smali2java.parser.cmd.asmd.add.Rule_cmdAddIntLit16;
import com.litecoding.smali2java.parser.cmd.asmd.add.Rule_cmdAddIntLit8;
import com.litecoding.smali2java.parser.cmd.asmd.add.Rule_cmdAddLong;
import com.litecoding.smali2java.parser.cmd.asmd.add.Rule_cmdAddLong2addr;
import com.litecoding.smali2java.parser.cmd.asmd.div.Rule_cmdDivDouble;
import com.litecoding.smali2java.parser.cmd.asmd.div.Rule_cmdDivDouble2addr;
import com.litecoding.smali2java.parser.cmd.asmd.div.Rule_cmdDivFloat;
import com.litecoding.smali2java.parser.cmd.asmd.div.Rule_cmdDivFloat2addr;
import com.litecoding.smali2java.parser.cmd.asmd.div.Rule_cmdDivInt;
import com.litecoding.smali2java.parser.cmd.asmd.div.Rule_cmdDivInt2addr;
import com.litecoding.smali2java.parser.cmd.asmd.div.Rule_cmdDivIntLit16;
import com.litecoding.smali2java.parser.cmd.asmd.div.Rule_cmdDivIntLit8;
import com.litecoding.smali2java.parser.cmd.asmd.div.Rule_cmdDivLong;
import com.litecoding.smali2java.parser.cmd.asmd.div.Rule_cmdDivLong2addr;
import com.litecoding.smali2java.parser.cmd.asmd.mul.Rule_cmdMulDouble;
import com.litecoding.smali2java.parser.cmd.asmd.mul.Rule_cmdMulDouble2addr;
import com.litecoding.smali2java.parser.cmd.asmd.mul.Rule_cmdMulFloat;
import com.litecoding.smali2java.parser.cmd.asmd.mul.Rule_cmdMulFloat2addr;
import com.litecoding.smali2java.parser.cmd.asmd.mul.Rule_cmdMulInt;
import com.litecoding.smali2java.parser.cmd.asmd.mul.Rule_cmdMulInt2addr;
import com.litecoding.smali2java.parser.cmd.asmd.mul.Rule_cmdMulIntLit16;
import com.litecoding.smali2java.parser.cmd.asmd.mul.Rule_cmdMulIntLit8;
import com.litecoding.smali2java.parser.cmd.asmd.mul.Rule_cmdMulLong;
import com.litecoding.smali2java.parser.cmd.asmd.mul.Rule_cmdMulLong2addr;
import com.litecoding.smali2java.parser.cmd.asmd.sub.Rule_cmdSubDouble;
import com.litecoding.smali2java.parser.cmd.asmd.sub.Rule_cmdSubDouble2addr;
import com.litecoding.smali2java.parser.cmd.asmd.sub.Rule_cmdSubFloat;
import com.litecoding.smali2java.parser.cmd.asmd.sub.Rule_cmdSubFloat2addr;
import com.litecoding.smali2java.parser.cmd.asmd.sub.Rule_cmdSubInt;
import com.litecoding.smali2java.parser.cmd.asmd.sub.Rule_cmdSubInt2addr;
import com.litecoding.smali2java.parser.cmd.asmd.sub.Rule_cmdSubLong;
import com.litecoding.smali2java.parser.cmd.asmd.sub.Rule_cmdSubLong2addr;
import com.litecoding.smali2java.parser.cmd.cmp.Rule_cmdCmpLong;
import com.litecoding.smali2java.parser.cmd.cmp.Rule_cmdCmpgDouble;
import com.litecoding.smali2java.parser.cmd.cmp.Rule_cmdCmpgFloat;
import com.litecoding.smali2java.parser.cmd.cmp.Rule_cmdCmplDouble;
import com.litecoding.smali2java.parser.cmd.cmp.Rule_cmdCmplFloat;
import com.litecoding.smali2java.parser.cmd.constz.Rule_cmdConst;
import com.litecoding.smali2java.parser.cmd.constz.Rule_cmdConst16;
import com.litecoding.smali2java.parser.cmd.constz.Rule_cmdConst4;
import com.litecoding.smali2java.parser.cmd.constz.Rule_cmdConstClass;
import com.litecoding.smali2java.parser.cmd.constz.Rule_cmdConstHigh16;
import com.litecoding.smali2java.parser.cmd.constz.Rule_cmdConstString;
import com.litecoding.smali2java.parser.cmd.constz.Rule_cmdConstStringJumbo;
import com.litecoding.smali2java.parser.cmd.constz.Rule_cmdConstWide;
import com.litecoding.smali2java.parser.cmd.constz.Rule_cmdConstWide16;
import com.litecoding.smali2java.parser.cmd.constz.Rule_cmdConstWide32;
import com.litecoding.smali2java.parser.cmd.constz.Rule_cmdConstWideHigh16;
import com.litecoding.smali2java.parser.cmd.get7put.aget.Rule_cmdAget;
import com.litecoding.smali2java.parser.cmd.get7put.aget.Rule_cmdAgetBoolean;
import com.litecoding.smali2java.parser.cmd.get7put.aget.Rule_cmdAgetByte;
import com.litecoding.smali2java.parser.cmd.get7put.aget.Rule_cmdAgetChar;
import com.litecoding.smali2java.parser.cmd.get7put.aget.Rule_cmdAgetObject;
import com.litecoding.smali2java.parser.cmd.get7put.aget.Rule_cmdAgetShort;
import com.litecoding.smali2java.parser.cmd.get7put.aget.Rule_cmdAgetWide;
import com.litecoding.smali2java.parser.cmd.get7put.aput.Rule_cmdAput;
import com.litecoding.smali2java.parser.cmd.get7put.aput.Rule_cmdAputBoolean;
import com.litecoding.smali2java.parser.cmd.get7put.aput.Rule_cmdAputByte;
import com.litecoding.smali2java.parser.cmd.get7put.aput.Rule_cmdAputChar;
import com.litecoding.smali2java.parser.cmd.get7put.aput.Rule_cmdAputObject;
import com.litecoding.smali2java.parser.cmd.get7put.aput.Rule_cmdAputShort;
import com.litecoding.smali2java.parser.cmd.get7put.aput.Rule_cmdAputWide;
import com.litecoding.smali2java.parser.cmd.get7put.iget.Rule_cmdIget;
import com.litecoding.smali2java.parser.cmd.get7put.iget.Rule_cmdIgetBoolean;
import com.litecoding.smali2java.parser.cmd.get7put.iget.Rule_cmdIgetByte;
import com.litecoding.smali2java.parser.cmd.get7put.iget.Rule_cmdIgetChar;
import com.litecoding.smali2java.parser.cmd.get7put.iget.Rule_cmdIgetObject;
import com.litecoding.smali2java.parser.cmd.get7put.iget.Rule_cmdIgetShort;
import com.litecoding.smali2java.parser.cmd.get7put.iget.Rule_cmdIgetWide;
import com.litecoding.smali2java.parser.cmd.get7put.iput.Rule_cmdIput;
import com.litecoding.smali2java.parser.cmd.get7put.iput.Rule_cmdIputBoolean;
import com.litecoding.smali2java.parser.cmd.get7put.iput.Rule_cmdIputByte;
import com.litecoding.smali2java.parser.cmd.get7put.iput.Rule_cmdIputChar;
import com.litecoding.smali2java.parser.cmd.get7put.iput.Rule_cmdIputObject;
import com.litecoding.smali2java.parser.cmd.get7put.iput.Rule_cmdIputShort;
import com.litecoding.smali2java.parser.cmd.get7put.iput.Rule_cmdIputWide;
import com.litecoding.smali2java.parser.cmd.get7put.sget.Rule_cmdSget;
import com.litecoding.smali2java.parser.cmd.get7put.sget.Rule_cmdSgetBoolean;
import com.litecoding.smali2java.parser.cmd.get7put.sget.Rule_cmdSgetByte;
import com.litecoding.smali2java.parser.cmd.get7put.sget.Rule_cmdSgetChar;
import com.litecoding.smali2java.parser.cmd.get7put.sget.Rule_cmdSgetObject;
import com.litecoding.smali2java.parser.cmd.get7put.sget.Rule_cmdSgetShort;
import com.litecoding.smali2java.parser.cmd.get7put.sget.Rule_cmdSgetWide;
import com.litecoding.smali2java.parser.cmd.get7put.sput.Rule_cmdSput;
import com.litecoding.smali2java.parser.cmd.get7put.sput.Rule_cmdSputBoolean;
import com.litecoding.smali2java.parser.cmd.get7put.sput.Rule_cmdSputByte;
import com.litecoding.smali2java.parser.cmd.get7put.sput.Rule_cmdSputChar;
import com.litecoding.smali2java.parser.cmd.get7put.sput.Rule_cmdSputObject;
import com.litecoding.smali2java.parser.cmd.get7put.sput.Rule_cmdSputShort;
import com.litecoding.smali2java.parser.cmd.get7put.sput.Rule_cmdSputWide;
import com.litecoding.smali2java.parser.cmd.gotoz.Rule_cmdGoto;
import com.litecoding.smali2java.parser.cmd.gotoz.Rule_cmdGoto16;
import com.litecoding.smali2java.parser.cmd.gotoz.Rule_cmdGoto32;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfEq;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfEqz;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfGe;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfGez;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfGt;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfGtz;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfLe;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfLez;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfLt;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfLtz;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfNe;
import com.litecoding.smali2java.parser.cmd.ifz.Rule_cmdIfNez;
import com.litecoding.smali2java.parser.cmd.int3long2.shl.Rule_cmdShlInt;
import com.litecoding.smali2java.parser.cmd.int3long2.shl.Rule_cmdShlInt2addr;
import com.litecoding.smali2java.parser.cmd.int3long2.shl.Rule_cmdShlIntLit8;
import com.litecoding.smali2java.parser.cmd.int3long2.shl.Rule_cmdShlLong;
import com.litecoding.smali2java.parser.cmd.int3long2.shl.Rule_cmdShlLong2addr;
import com.litecoding.smali2java.parser.cmd.int3long2.shr.Rule_cmdShrInt;
import com.litecoding.smali2java.parser.cmd.int3long2.shr.Rule_cmdShrInt2addr;
import com.litecoding.smali2java.parser.cmd.int3long2.shr.Rule_cmdShrIntLit8;
import com.litecoding.smali2java.parser.cmd.int3long2.shr.Rule_cmdShrLong;
import com.litecoding.smali2java.parser.cmd.int3long2.shr.Rule_cmdShrLong2addr;
import com.litecoding.smali2java.parser.cmd.int3long2.ushr.Rule_cmdUshrInt;
import com.litecoding.smali2java.parser.cmd.int3long2.ushr.Rule_cmdUshrInt2addr;
import com.litecoding.smali2java.parser.cmd.int3long2.ushr.Rule_cmdUshrIntLit8;
import com.litecoding.smali2java.parser.cmd.int3long2.ushr.Rule_cmdUshrLong;
import com.litecoding.smali2java.parser.cmd.int3long2.ushr.Rule_cmdUshrLong2addr;
import com.litecoding.smali2java.parser.cmd.invoke.Rule_cmdInvokeDirect;
import com.litecoding.smali2java.parser.cmd.invoke.Rule_cmdInvokeDirectRange;
import com.litecoding.smali2java.parser.cmd.invoke.Rule_cmdInvokeInterface;
import com.litecoding.smali2java.parser.cmd.invoke.Rule_cmdInvokeInterfaceRange;
import com.litecoding.smali2java.parser.cmd.invoke.Rule_cmdInvokeStatic;
import com.litecoding.smali2java.parser.cmd.invoke.Rule_cmdInvokeStaticRange;
import com.litecoding.smali2java.parser.cmd.invoke.Rule_cmdInvokeSuper;
import com.litecoding.smali2java.parser.cmd.invoke.Rule_cmdInvokeSuperRange;
import com.litecoding.smali2java.parser.cmd.invoke.Rule_cmdInvokeVirtual;
import com.litecoding.smali2java.parser.cmd.invoke.Rule_cmdInvokeVirtualRange;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMove;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMove16;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMoveException;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMoveFrom16;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMoveObject;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMoveObject16;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMoveObjectFrom16;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMoveResult;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMoveResultObject;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMoveResultWide;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMoveWide;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMoveWide16;
import com.litecoding.smali2java.parser.cmd.move.Rule_cmdMoveWideFrom16;
import com.litecoding.smali2java.parser.cmd.neg.Rule_cmdNegDouble;
import com.litecoding.smali2java.parser.cmd.neg.Rule_cmdNegFloat;
import com.litecoding.smali2java.parser.cmd.neg.Rule_cmdNegInt;
import com.litecoding.smali2java.parser.cmd.neg.Rule_cmdNegLong;
import com.litecoding.smali2java.parser.cmd.newz.Rule_cmdNewArray;
import com.litecoding.smali2java.parser.cmd.newz.Rule_cmdNewInstance;
import com.litecoding.smali2java.parser.cmd.rem.Rule_cmdRemDouble;
import com.litecoding.smali2java.parser.cmd.rem.Rule_cmdRemDouble2addr;
import com.litecoding.smali2java.parser.cmd.rem.Rule_cmdRemFloat;
import com.litecoding.smali2java.parser.cmd.rem.Rule_cmdRemFloat2addr;
import com.litecoding.smali2java.parser.cmd.rem.Rule_cmdRemInt;
import com.litecoding.smali2java.parser.cmd.rem.Rule_cmdRemInt2addr;
import com.litecoding.smali2java.parser.cmd.rem.Rule_cmdRemIntLit16;
import com.litecoding.smali2java.parser.cmd.rem.Rule_cmdRemIntLit8;
import com.litecoding.smali2java.parser.cmd.rem.Rule_cmdRemLong;
import com.litecoding.smali2java.parser.cmd.rem.Rule_cmdRemLong2addr;
import com.litecoding.smali2java.parser.cmd.returnz.Rule_cmdReturn;
import com.litecoding.smali2java.parser.cmd.returnz.Rule_cmdReturnObject;
import com.litecoding.smali2java.parser.cmd.returnz.Rule_cmdReturnVoid;
import com.litecoding.smali2java.parser.cmd.returnz.Rule_cmdReturnWide;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdDoubleToFloat;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdDoubleToInt;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdDoubleToLong;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdFloatToDouble;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdFloatToInt;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdFloatToLong;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdIntToByte;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdIntToChar;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdIntToDouble;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdIntToFloat;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdIntToLong;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdIntToShort;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdLongToDouble;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdLongToFloat;
import com.litecoding.smali2java.parser.cmd.to.Rule_cmdLongToInt;
import com.litecoding.smali2java.parser.method.MethodParamRule;
import com.litecoding.smali2java.parser.method.Rule_classClass;
import com.litecoding.smali2java.parser.method.Rule_classField;
import com.litecoding.smali2java.parser.method.Rule_classHeader;
import com.litecoding.smali2java.parser.method.Rule_classImplements;
import com.litecoding.smali2java.parser.method.Rule_classMethod;
import com.litecoding.smali2java.parser.method.Rule_classMethodProto;
import com.litecoding.smali2java.parser.method.Rule_classSource;
import com.litecoding.smali2java.parser.method.Rule_classSuper;
import com.litecoding.smali2java.parser.method.Rule_methodBody;
import com.litecoding.smali2java.parser.method.Rule_methodLocal;
import com.litecoding.smali2java.parser.method.Rule_methodParam;
import com.litecoding.smali2java.parser.method.Rule_methodRegisters;
import com.litecoding.smali2java.parser.method.Rule_smali;
import com.litecoding.smali2java.parser.smali.Rule_accessMode;
import com.litecoding.smali2java.parser.smali.Rule_annotation;
import com.litecoding.smali2java.parser.smali.Rule_annotationBody;
import com.litecoding.smali2java.parser.smali.Rule_annotationVisibility;
import com.litecoding.smali2java.parser.smali.Rule_boolValue;
import com.litecoding.smali2java.parser.smali.Rule_classConstructorName;
import com.litecoding.smali2java.parser.smali.Rule_className;
import com.litecoding.smali2java.parser.smali.Rule_codeRegister;
import com.litecoding.smali2java.parser.smali.Rule_codeRegister64;
import com.litecoding.smali2java.parser.smali.Rule_codeRegisterGroup;
import com.litecoding.smali2java.parser.smali.Rule_codeRegisterP;
import com.litecoding.smali2java.parser.smali.Rule_codeRegisterP64;
import com.litecoding.smali2java.parser.smali.Rule_codeRegisterRet;
import com.litecoding.smali2java.parser.smali.Rule_codeRegisterRet64;
import com.litecoding.smali2java.parser.smali.Rule_codeRegisterV;
import com.litecoding.smali2java.parser.smali.Rule_codeRegisterV64;
import com.litecoding.smali2java.parser.smali.Rule_codeRegisterV64Dst;
import com.litecoding.smali2java.parser.smali.Rule_codeRegisterVDst;
import com.litecoding.smali2java.parser.smali.Rule_comment;
import com.litecoding.smali2java.parser.smali.Rule_commentSequence;
import com.litecoding.smali2java.parser.smali.Rule_dirAnnotation;
import com.litecoding.smali2java.parser.smali.Rule_dirClass;
import com.litecoding.smali2java.parser.smali.Rule_dirEnd;
import com.litecoding.smali2java.parser.smali.Rule_dirEndAnnotation;
import com.litecoding.smali2java.parser.smali.Rule_dirEndField;
import com.litecoding.smali2java.parser.smali.Rule_dirEndMethod;
import com.litecoding.smali2java.parser.smali.Rule_dirEndSubannotation;
import com.litecoding.smali2java.parser.smali.Rule_dirField;
import com.litecoding.smali2java.parser.smali.Rule_dirImplements;
import com.litecoding.smali2java.parser.smali.Rule_dirLocal;
import com.litecoding.smali2java.parser.smali.Rule_dirMethod;
import com.litecoding.smali2java.parser.smali.Rule_dirRegisters;
import com.litecoding.smali2java.parser.smali.Rule_dirSource;
import com.litecoding.smali2java.parser.smali.Rule_dirSubannotation;
import com.litecoding.smali2java.parser.smali.Rule_dirSuper;
import com.litecoding.smali2java.parser.smali.Rule_emptyLine;
import com.litecoding.smali2java.parser.smali.Rule_escSymbol;
import com.litecoding.smali2java.parser.smali.Rule_fileName;
import com.litecoding.smali2java.parser.smali.Rule_intDecValue;
import com.litecoding.smali2java.parser.smali.Rule_intHexValue;
import com.litecoding.smali2java.parser.smali.Rule_intValue;
import com.litecoding.smali2java.parser.smali.Rule_interfaceMode;
import com.litecoding.smali2java.parser.smali.Rule_label;
import com.litecoding.smali2java.parser.smali.Rule_listSeparator;
import com.litecoding.smali2java.parser.smali.Rule_optPadding;
import com.litecoding.smali2java.parser.smali.Rule_optWidePadding;
import com.litecoding.smali2java.parser.smali.Rule_padding;
import com.litecoding.smali2java.parser.smali.Rule_qualifier;
import com.litecoding.smali2java.parser.smali.Rule_skipLine;
import com.litecoding.smali2java.parser.smali.Rule_smaliClassRef;
import com.litecoding.smali2java.parser.smali.Rule_smaliConstructorName;
import com.litecoding.smali2java.parser.smali.Rule_smaliFieldRef;
import com.litecoding.smali2java.parser.smali.Rule_smaliMethodRef;
import com.litecoding.smali2java.parser.smali.Rule_strValue;
import com.litecoding.smali2java.parser.smali.Rule_todoStubLine;
import com.litecoding.smali2java.parser.smali.Rule_type;
import com.litecoding.smali2java.parser.smali.Rule_value;
import com.litecoding.smali2java.parser.smali.Rule_widePadding;
import com.litecoding.smali2java.parser.text.Rule_ALPHA;
import com.litecoding.smali2java.parser.text.Rule_COLON;
import com.litecoding.smali2java.parser.text.Rule_COMMA;
import com.litecoding.smali2java.parser.text.Rule_CR;
import com.litecoding.smali2java.parser.text.Rule_CRLF;
import com.litecoding.smali2java.parser.text.Rule_DIGIT;
import com.litecoding.smali2java.parser.text.Rule_DOT;
import com.litecoding.smali2java.parser.text.Rule_EQ;
import com.litecoding.smali2java.parser.text.Rule_HASH;
import com.litecoding.smali2java.parser.text.Rule_HEXDIG;
import com.litecoding.smali2java.parser.text.Rule_HTAB;
import com.litecoding.smali2java.parser.text.Rule_LF;
import com.litecoding.smali2java.parser.text.Rule_QUOT;
import com.litecoding.smali2java.parser.text.Rule_SEMICOLON;
import com.litecoding.smali2java.parser.text.Rule_SP;
import com.litecoding.smali2java.parser.text.Rule_UNDERSCORE;
import com.litecoding.smali2java.parser.text.Rule_VCHAR;

public interface Visitor
{
  public Object visit(Rule_padding rule);
  public Object visit(Rule_optPadding rule);
  public Object visit(Rule_widePadding rule);
  public Object visit(Rule_optWidePadding rule);
  public Object visit(Rule_listSeparator rule);
  public Object visit(Rule_escSymbol rule);
  public Object visit(Rule_qualifier rule);
  public Object visit(Rule_className rule);
  public Object visit(Rule_commentSequence rule);
  public Object visit(Rule_comment rule);
  public Object visit(Rule_emptyLine rule);
  public Object visit(Rule_skipLine rule);
  public Object visit(Rule_fileName rule);
  public Object visit(Rule_accessMode rule);
  public Object visit(Rule_interfaceMode rule);
  public Object visit(Rule_type rule);
  public Object visit(Rule_boolValue rule);
  public Object visit(Rule_intDecValue rule);
  public Object visit(Rule_intHexValue rule);
  public Object visit(Rule_intValue rule);
  public Object visit(Rule_strValue rule);
  public Object visit(Rule_value rule);
  public Object visit(Rule_codeLabel rule);
  public Object visit(Rule_codeRegisterP rule);
  public Object visit(Rule_codeRegisterP64 rule);
  public Object visit(Rule_codeRegisterV rule);
  public Object visit(Rule_codeRegisterV64 rule);
  public Object visit(Rule_codeRegisterVDst rule);
  public Object visit(Rule_codeRegisterV64Dst rule);
  public Object visit(Rule_codeRegister rule);
  public Object visit(Rule_codeRegister64 rule);
  public Object visit(Rule_codeRegisterRet rule);
  public Object visit(Rule_codeRegisterRet64 rule);
  public Object visit(Rule_codeRegisterGroup rule);
  public Object visit(Rule_dirAnnotation rule);
  public Object visit(Rule_dirClass rule);
  public Object visit(Rule_dirEnd rule);
  public Object visit(Rule_dirEndAnnotation rule);
  public Object visit(Rule_dirEndField rule);
  public Object visit(Rule_dirEndMethod rule);
  public Object visit(Rule_dirEndSubannotation rule);
  public Object visit(Rule_dirImplements rule);
  public Object visit(Rule_dirField rule);
  public Object visit(Rule_dirLocal rule);
  public Object visit(Rule_dirMethod rule);
  public Object visit(Rule_dirRegisters rule);
  public Object visit(Rule_dirSubannotation rule);
  public Object visit(Rule_dirSuper rule);
  public Object visit(Rule_dirSource rule);
  public Object visit(Rule_smali rule);
  public Object visit(Rule_todoStubLine rule);
  public Object visit(Rule_classHeader rule);
  public Object visit(Rule_classClass rule);
  public Object visit(Rule_classSuper rule);
  public Object visit(Rule_classSource rule);
  public Object visit(Rule_classImplements rule);
	Object visit(Rule_methodLocals rule);
  public Object visit(Rule_methodParam rule);
	Object visit(MethodParamRule rule);
  public Object visit(Rule_methodPrologue rule);
  public Object visit(Rule_methodLine rule);
  public Object visit(Rule_methodRegisters rule);
  public Object visit(Rule_methodLocal rule);
  public Object visit(Rule_annotation rule);
  public Object visit(Rule_annotationVisibility rule);
  public Object visit(Rule_annotationBody rule);
  public Object visit(Rule_classField rule);
  public Object visit(Rule_classMethod rule);
  public Object visit(Rule_classConstructorName rule);
  public Object visit(Rule_classMethodProto rule);
  public Object visit(Rule_methodBody rule);
  public Object visit(Rule_label rule);
  public Object visit(Rule_smaliConstructorName rule);
  public Object visit(Rule_smaliClassRef rule);
  public Object visit(Rule_smaliFieldRef rule);
  public Object visit(Rule_smaliMethodRef rule);
  public Object visit(Rule_HTAB rule);
  public Object visit(Rule_CR rule);
  public Object visit(Rule_LF rule);
  public Object visit(Rule_SP rule);
  public Object visit(Rule_CRLF rule);
  public Object visit(Rule_QUOT rule);
  public Object visit(Rule_HASH rule);
  public Object visit(Rule_COMMA rule);
  public Object visit(Rule_DOT rule);
  public Object visit(Rule_COLON rule);
  public Object visit(Rule_SEMICOLON rule);
  public Object visit(Rule_EQ rule);
  public Object visit(Rule_UNDERSCORE rule);
  public Object visit(Rule_ALPHA rule);
  public Object visit(Rule_DIGIT rule);
  public Object visit(Rule_HEXDIG rule);
  public Object visit(Rule_VCHAR rule);
  public Object visit(Rule_cmdAny rule);
  public Object visit(Rule_cmdAddFloat rule);
  public Object visit(Rule_cmdAddFloat2addr rule);
  public Object visit(Rule_cmdAddDouble rule);
  public Object visit(Rule_cmdAddDouble2addr rule);
  public Object visit(Rule_cmdAddInt rule);
  public Object visit(Rule_cmdAddInt2addr rule);
  public Object visit(Rule_cmdAddIntLit16 rule);
  public Object visit(Rule_cmdAddIntLit8 rule);
  public Object visit(Rule_cmdAddLong rule);
  public Object visit(Rule_cmdAddLong2addr rule);
  public Object visit(Rule_cmdAndInt rule);
  public Object visit(Rule_cmdAndInt2addr rule);
  public Object visit(Rule_cmdAndIntLit16 rule);
  public Object visit(Rule_cmdAndIntLit8 rule);
  public Object visit(Rule_cmdAndLong rule);
  public Object visit(Rule_cmdAndLong2addr rule);
  public Object visit(Rule_cmdAget rule);
  public Object visit(Rule_cmdAgetBoolean rule);
  public Object visit(Rule_cmdAgetByte rule);
  public Object visit(Rule_cmdAgetChar rule);
  public Object visit(Rule_cmdAgetObject rule);
  public Object visit(Rule_cmdAgetShort rule);
  public Object visit(Rule_cmdAgetWide rule);
  public Object visit(Rule_cmdAput rule);
  public Object visit(Rule_cmdAputBoolean rule);
  public Object visit(Rule_cmdAputByte rule);
  public Object visit(Rule_cmdAputChar rule);
  public Object visit(Rule_cmdAputObject rule);
  public Object visit(Rule_cmdAputShort rule);
  public Object visit(Rule_cmdAputWide rule);
  public Object visit(Rule_cmdArrayLength rule);
  public Object visit(Rule_cmdCheckCast rule);
  public Object visit(Rule_cmdCmpgDouble rule);
  public Object visit(Rule_cmdCmpgFloat rule);
  public Object visit(Rule_cmdCmplDouble rule);
  public Object visit(Rule_cmdCmplFloat rule);
  public Object visit(Rule_cmdCmpLong rule);
  public Object visit(Rule_cmdConst rule);
  public Object visit(Rule_cmdConst16 rule);
  public Object visit(Rule_cmdConst4 rule);
  public Object visit(Rule_cmdConstClass rule);
  public Object visit(Rule_cmdConstHigh16 rule);
  public Object visit(Rule_cmdConstString rule);
  public Object visit(Rule_cmdConstStringJumbo rule);
  public Object visit(Rule_cmdConstWide rule);
  public Object visit(Rule_cmdConstWide16 rule);
  public Object visit(Rule_cmdConstWide32 rule);
  public Object visit(Rule_cmdConstWideHigh16 rule);
  public Object visit(Rule_cmdDivFloat rule);
  public Object visit(Rule_cmdDivFloat2addr rule);
  public Object visit(Rule_cmdDivDouble rule);
  public Object visit(Rule_cmdDivDouble2addr rule);
  public Object visit(Rule_cmdDivInt rule);
  public Object visit(Rule_cmdDivInt2addr rule);
  public Object visit(Rule_cmdDivIntLit16 rule);
  public Object visit(Rule_cmdDivIntLit8 rule);
  public Object visit(Rule_cmdDivLong rule);
  public Object visit(Rule_cmdDivLong2addr rule);
  public Object visit(Rule_cmdDoubleToFloat rule);
  public Object visit(Rule_cmdDoubleToInt rule);
  public Object visit(Rule_cmdDoubleToLong rule);
  public Object visit(Rule_cmdFillArrayData rule);
  public Object visit(Rule_cmdFilledNewArray rule);
  public Object visit(Rule_cmdFilledNewArrayRange rule);
  public Object visit(Rule_cmdFloatToDouble rule);
  public Object visit(Rule_cmdFloatToInt rule);
  public Object visit(Rule_cmdFloatToLong rule);
  public Object visit(Rule_cmdGoto rule);
  public Object visit(Rule_cmdGoto16 rule);
  public Object visit(Rule_cmdGoto32 rule);
  public Object visit(Rule_cmdIfEq rule);
  public Object visit(Rule_cmdIfEqz rule);
  public Object visit(Rule_cmdIfGe rule);
  public Object visit(Rule_cmdIfGez rule);
  public Object visit(Rule_cmdIfGt rule);
  public Object visit(Rule_cmdIfGtz rule);
  public Object visit(Rule_cmdIfLe rule);
  public Object visit(Rule_cmdIfLez rule);
  public Object visit(Rule_cmdIfLt rule);
  public Object visit(Rule_cmdIfLtz rule);
  public Object visit(Rule_cmdIfNe rule);
  public Object visit(Rule_cmdIfNez rule);
  public Object visit(Rule_cmdIget rule);
  public Object visit(Rule_cmdIgetBoolean rule);
  public Object visit(Rule_cmdIgetByte rule);
  public Object visit(Rule_cmdIgetChar rule);
  public Object visit(Rule_cmdIgetObject rule);
  public Object visit(Rule_cmdIgetShort rule);
  public Object visit(Rule_cmdIgetWide rule);
  public Object visit(Rule_cmdInstanceOf rule);
  public Object visit(Rule_cmdIntToByte rule);
  public Object visit(Rule_cmdIntToChar rule);
  public Object visit(Rule_cmdIntToDouble rule);
  public Object visit(Rule_cmdIntToFloat rule);
  public Object visit(Rule_cmdIntToLong rule);
  public Object visit(Rule_cmdIntToShort rule);
  public Object visit(Rule_cmdInvokeDirect rule);
  public Object visit(Rule_cmdInvokeDirectRange rule);
  public Object visit(Rule_cmdInvokeInterface rule);
  public Object visit(Rule_cmdInvokeInterfaceRange rule);
  public Object visit(Rule_cmdInvokeStatic rule);
  public Object visit(Rule_cmdInvokeStaticRange rule);
  public Object visit(Rule_cmdInvokeSuper rule);
  public Object visit(Rule_cmdInvokeSuperRange rule);
  public Object visit(Rule_cmdInvokeVirtual rule);
  public Object visit(Rule_cmdInvokeVirtualRange rule);
  public Object visit(Rule_cmdIput rule);
  public Object visit(Rule_cmdIputBoolean rule);
  public Object visit(Rule_cmdIputByte rule);
  public Object visit(Rule_cmdIputChar rule);
  public Object visit(Rule_cmdIputObject rule);
  public Object visit(Rule_cmdIputShort rule);
  public Object visit(Rule_cmdIputWide rule);
  public Object visit(Rule_cmdLongToDouble rule);
  public Object visit(Rule_cmdLongToFloat rule);
  public Object visit(Rule_cmdLongToInt rule);
  public Object visit(Rule_cmdMonitorEnter rule);
  public Object visit(Rule_cmdMonitorExit rule);
  public Object visit(Rule_cmdMove rule);
  public Object visit(Rule_cmdMove16 rule);
  public Object visit(Rule_cmdMoveException rule);
  public Object visit(Rule_cmdMoveFrom16 rule);
  public Object visit(Rule_cmdMoveObject rule);
  public Object visit(Rule_cmdMoveObject16 rule);
  public Object visit(Rule_cmdMoveObjectFrom16 rule);
  public Object visit(Rule_cmdMoveResult rule);
  public Object visit(Rule_cmdMoveResultObject rule);
  public Object visit(Rule_cmdMoveResultWide rule);
  public Object visit(Rule_cmdMoveWide rule);
  public Object visit(Rule_cmdMoveWide16 rule);
  public Object visit(Rule_cmdMoveWideFrom16 rule);
  public Object visit(Rule_cmdMulFloat rule);
  public Object visit(Rule_cmdMulFloat2addr rule);
  public Object visit(Rule_cmdMulDouble rule);
  public Object visit(Rule_cmdMulDouble2addr rule);
  public Object visit(Rule_cmdMulInt rule);
  public Object visit(Rule_cmdMulInt2addr rule);
  public Object visit(Rule_cmdMulIntLit16 rule);
  public Object visit(Rule_cmdMulIntLit8 rule);
  public Object visit(Rule_cmdMulLong rule);
  public Object visit(Rule_cmdMulLong2addr rule);
  public Object visit(Rule_cmdNegDouble rule);
  public Object visit(Rule_cmdNegFloat rule);
  public Object visit(Rule_cmdNegInt rule);
  public Object visit(Rule_cmdNegLong rule);
  public Object visit(Rule_cmdNewArray rule);
  public Object visit(Rule_cmdNewInstance rule);
  public Object visit(Rule_cmdNop rule);
  public Object visit(Rule_cmdNotInt rule);
  public Object visit(Rule_cmdNotLong rule);
  public Object visit(Rule_cmdOrInt rule);
  public Object visit(Rule_cmdOrInt2addr rule);
  public Object visit(Rule_cmdOrIntLit16 rule);
  public Object visit(Rule_cmdOrIntLit8 rule);
  public Object visit(Rule_cmdOrLong rule);
  public Object visit(Rule_cmdOrLong2addr rule);
  public Object visit(Rule_cmdPackedSwitch rule);
  public Object visit(Rule_cmdRemFloat rule);
  public Object visit(Rule_cmdRemFloat2addr rule);
  public Object visit(Rule_cmdRemDouble rule);
  public Object visit(Rule_cmdRemDouble2addr rule);
  public Object visit(Rule_cmdRemInt rule);
  public Object visit(Rule_cmdRemInt2addr rule);
  public Object visit(Rule_cmdRemIntLit16 rule);
  public Object visit(Rule_cmdRemIntLit8 rule);
  public Object visit(Rule_cmdRemLong rule);
  public Object visit(Rule_cmdRemLong2addr rule);
  public Object visit(Rule_cmdReturn rule);
  public Object visit(Rule_cmdReturnObject rule);
  public Object visit(Rule_cmdReturnVoid rule);
  public Object visit(Rule_cmdReturnWide rule);
  public Object visit(Rule_cmdRsubInt rule);
  public Object visit(Rule_cmdRsubIntLit8 rule);
  public Object visit(Rule_cmdSget rule);
  public Object visit(Rule_cmdSgetBoolean rule);
  public Object visit(Rule_cmdSgetByte rule);
  public Object visit(Rule_cmdSgetChar rule);
  public Object visit(Rule_cmdSgetObject rule);
  public Object visit(Rule_cmdSgetShort rule);
  public Object visit(Rule_cmdSgetWide rule);
  public Object visit(Rule_cmdShlInt rule);
  public Object visit(Rule_cmdShlInt2addr rule);
  public Object visit(Rule_cmdShlIntLit8 rule);
  public Object visit(Rule_cmdShlLong rule);
  public Object visit(Rule_cmdShlLong2addr rule);
  public Object visit(Rule_cmdShrInt rule);
  public Object visit(Rule_cmdShrInt2addr rule);
  public Object visit(Rule_cmdShrIntLit8 rule);
  public Object visit(Rule_cmdShrLong rule);
  public Object visit(Rule_cmdShrLong2addr rule);
  public Object visit(Rule_cmdSparseSwitch rule);
  public Object visit(Rule_cmdSput rule);
  public Object visit(Rule_cmdSputBoolean rule);
  public Object visit(Rule_cmdSputByte rule);
  public Object visit(Rule_cmdSputChar rule);
  public Object visit(Rule_cmdSputObject rule);
  public Object visit(Rule_cmdSputShort rule);
  public Object visit(Rule_cmdSputWide rule);
  public Object visit(Rule_cmdSubFloat rule);
  public Object visit(Rule_cmdSubFloat2addr rule);
  public Object visit(Rule_cmdSubDouble rule);
  public Object visit(Rule_cmdSubDouble2addr rule);
  public Object visit(Rule_cmdSubInt rule);
  public Object visit(Rule_cmdSubInt2addr rule);
  public Object visit(Rule_cmdSubLong rule);
  public Object visit(Rule_cmdSubLong2addr rule);
  public Object visit(Rule_cmdThrow rule);
  public Object visit(Rule_cmdUshrInt rule);
  public Object visit(Rule_cmdUshrInt2addr rule);
  public Object visit(Rule_cmdUshrIntLit8 rule);
  public Object visit(Rule_cmdUshrLong rule);
  public Object visit(Rule_cmdUshrLong2addr rule);
  public Object visit(Rule_cmdXorInt rule);
  public Object visit(Rule_cmdXorInt2addr rule);
  public Object visit(Rule_cmdXorIntLit16 rule);
  public Object visit(Rule_cmdXorIntLit8 rule);
  public Object visit(Rule_cmdXorLong rule);
  public Object visit(Rule_cmdXorLong2addr rule);

  public Object visit(Terminal_StringValue value);
  public Object visit(Terminal_NumericValue value);
}

/* -----------------------------------------------------------------------------
 * eof
 * -----------------------------------------------------------------------------
 */
